### PR TITLE
Enable autoconf build

### PR DESCRIPTION
**Pull request by amitay**
Improve the build system by using autoconf.  All the programs (link_stack, qtrace2dis, qtrace-bbv, ptracer) are now built using top-level build.  I have left out the the tests under ptracer/tests out.

This also fixes some of the build failures on fedora 27 with gcc7.

### CODE REVIEW

**Comment by antonblanchard** [comment]
Thanks Amitay, looks great.

**Comment by antonblanchard** [comment]
Could we search for libbfd-multiarch.so and libopcodes-multiarch.so before the base versions? That would allow us to disassemble traces on other architectures, at least on Ubuntu.

**Comment by amitay** [comment]
Sure.. Do you know a machine which already has multiarch versions of libbfd and libopcodes installed?

**Comment by amitay** [comment]
Aargh.. now I understand.. you want to disassemble on your laptop..  :-)  I will build a VM with ubuntu..

**Pull request merged**
